name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Deploy to render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ RENDER.RENDER_SERVICE_ID }}?key=${{ RENDER.RENDER_API_KEY }}
