name: Trigger Render Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  test:
    name: Deploy to render
    runs-on: ubuntu-latest
    environment: RENDER
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}
